services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./scripts/src/db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  jupyter:
    build: 
      context: .
      args:
        DIR_WORK: "/usr/src"
        ENV_YML: "environment.yaml"
        VENV: "bioinfo"
        REQ_TXT: "requirements.txt"
    image: tyamadabiodataeng/py-metabolomics
    container_name: jupyter
    command: mamba run --name bioinfo jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./scripts:/usr/src
    tty: true
    stdin_open: true

volumes:
  postgres_data:
